version = 3.8.3
runner.dialect = scala3

maxColumn = 120
align.preset = more
align.multiline = false

rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
rewrite.redundantBraces.stringInterpolation = true
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = yes

indent.main = 2
indent.callSite = 2
indent.defnSite = 2

newlines.source = keep
newlines.topLevelStatements = [before, after]

docstrings.style = Asterisk
docstrings.wrap = yes
